Manajemen Buku pada Role Pustakawan
nurfachmi/perpustakaan pull request #1
Opened 2023-10-01 18:13 UTC by mohammad-firmansyah

- menambahkan migration dan models untuk buku dan kategori buku
- menambahkan controller resources untuk endpoint buku
- menambahkan halaman index dan create (belum selesai)

2023-10-01 18:15 UTC, mohammad-firmansyah commented
hacktoberfest tag pls

2023-10-02 02:18 UTC, AaEzha commented
> hacktoberfest tag pls

reponya sudah ada topic hacktoberfest dan sudah ditambahkan label `hacktoberfest-accepted` supaya semakin di depan. ha ha ha.

2023-10-02 02:51 UTC, AaEzha requested changes
Ada beberapa masukan dari saya. Jika ada yg kurang dipahami, monggo ditanyakan saja.

2023-10-02 02:51 UTC, AaEzha commented on app/Http/Controllers/BookController.php
> +    private $title = "Books";
Kalau ngikuti konvensi repo ini, pada bagian ini harus ditulis dalam bentuk singular. 

dalam kasus ini, "Book".

2023-10-02 02:51 UTC, AaEzha commented on app/Http/Controllers/Datatables/BookDatatables.php
> +        $query = Book::all();
Karena eloquent-nya akan di-handle oleh Yajra, maka kita tidak boleh menggunakan method untuk mengambil data, seperti `all()`, `paginate()`, `get()` atau lainnya.

Supaya biar gak keliatan buntung, coba aja diurutkan berdasarkan judul.

```php
$query = Book::orderBy('title');
```

2023-10-02 02:51 UTC, AaEzha commented on app/Http/Controllers/Datatables/BookDatatables.php
> +                );
untuk link edit dan hapus, sudah dihandle oleh baris di atasnya, pada `edit-url`. jadi, barisan ini dihapus saja.

2023-10-02 03:32 UTC, mohammad-firmansyah commented on app/Http/Controllers/Datatables/BookDatatables.php
> +                );
yang ini ketika saya hapus array_push nya jadi hilang ya mas menunya ?

2023-10-02 08:11 UTC, AaEzha commented on app/Http/Controllers/Datatables/BookDatatables.php
> +                );
oh walaah. mestinya yg di atasnya tadi gak perlu dihapus. cukup yg dikomentarin aja yg dihapus, mas.

2023-10-02 09:16 UTC, mohammad-firmansyah commented on app/Http/Controllers/Datatables/BookDatatables.php
> +                );
ok mas sudah saya delete dan kembalikan yang atas tadi

2023-10-02 12:58 UTC, AaEzha commented on app/Http/Controllers/Datatables/BookDatatables.php
> +                );
aman kan ya, mas?

2023-10-05 07:35 UTC, mohammad-firmansyah commented
maaf mas baru bisa ngerjain lagi ada kesibukan di kampus hihi

2023-10-05 07:35 UTC, mohammad-firmansyah commented
sudah saya tambahkan semua untuk crud mas mohon diperiksa @AaEzha

2023-10-05 07:35 UTC, mohammad-firmansyah commented on app/Http/Controllers/Datatables/BookDatatables.php
> +                );
aman mas

2023-10-05 13:31 UTC, AaEzha approved these changes
Menurut saya ini sudah cukup. Bisa dikembangkan lagi kemudian.

2023-10-05 13:31 UTC, merged